### ISSUE TITLE
Error message when using CSS variables

### ISSUE THREAD

**Issue by mririgoyen** [glen-84/vscode-sass-lint#25]
When using css variables inside SCSS files, the `vscode-sass-lint` plugin constantly throws errors and does not continue validating the rest of the file.

The error message that is shown is:
```
vscode-sass-lint: 'Cannot read property 'is' of null' while validating: /Users/mirigoyen/Git/projectname/client/components/WelcomeScreen/WelcomeScreen.scss stacktrace: TypeError: Cannot read property 'is' of null at processNode (/Users/mirigoyen/Git/projectname/node_modules/sass-lint/lib/rules/indentation.js:177:44) at processNode (/Users/mirigoyen/Git/projectname/node_modules/sass-lint/lib/rules/indentation.js:204:9) at processNode (/Users/mirigoyen/Git/projectname/node_modules/sass-lint/lib/rules/indentation.js:204:9) at processNode (/Users/mirigoyen/Git/projectname/node_modules/sass-lint/lib/rules/indentation.js:204:9) at processNode (/Users/mirigoyen/Git/projectname/node_modules/sass-lint/lib/rules/indentation.js:204:9) at processNode (/Users/mirigoyen/Git/projectname/node_modules/sass-lint/lib/rules/indentation.js:204:9) at Object.detect (/Users/mirigoyen/Git/projectname/node_modules/sass-lint/lib/rules/indentation.js:208:5) at /Users/mirigoyen/Git/projectname/node_modules/sa...
```

A couple sample files look like:
```
:root {
  --primary: rgb(var(--primary-color));
  --secondary: rgb(var(--secondary-color));
}
```

```
.welcome-screen {
  align-items: center;
  background-color: $black;
  background-image: url('../../assets/landing-bg.png'), radial-gradient(rgba(var(--secondary-color), 1), rgba(var(--secondary-color), .7));
  display: flex;
  height: 100vh;
  justify-content: center;
}
```

**Comment by glen-84** [comment]
Hi Michael,

Could you please provide the following information?:

* OS version
* VS Code version
* Node.js version
* sass-lint version
* Extension configuration
* .sass-lint.yml configuration
* Location of .sass-lint.yml file in relation to the file being linted
* etc.

Judging by the stacktrace, this looks like an issue with the sass-lint library. Make sure that you're using the latest version (v1.12.1).

Thanks.
